### ISSUE TITLE
Exception on sample start

### ISSUE THREAD

**Issue by SerVB** [ruslanys/telegraff#23]
There is an exception when starting the telegraff-sample. The bot works fine. However, it's annoying:

```
C:\Users\servb\Documents\Shared\telegraff\telegraff-sample>.\build\install\telegraff-sample\bin\telegraff-sample


  ############################################################################
  ##************************************************************************##
  ##***************&8##o********************************o8#8&***************##
  ##************o###o***&******************************&:**o###o************##
  ##************###**********o########&**&########o**********###************##
  ##************###**********######################**********###************##
  ##************####&*****8##########################8*****&####************##
  ##************o######################88######################o************##
  ##***************8################8o****o8################8***************##
  ##*******************&&8###8&&:**************:&&8###8&&*******************##
  ##************************************************************************##
  ############################################################################

2019-11-03 09:29:59.614  INFO 1916 --- [           main] m.r.telegraff.sample.ApplicationKt       : Starting ApplicationKt v1.0.0 on NUC with PID 1916 (C:\Users\servb\Documents\Shared\telegraff\telegraff-sample\build\install\telegraff-sample\lib\telegraff-sample-1.0.0.jar started by servb in C:\Users\servb\Documents\Shared\telegraff\telegraff-sample)
2019-11-03 09:29:59.622  INFO 1916 --- [           main] m.r.telegraff.sample.ApplicationKt       : No active profile set, falling back to default profiles: default
2019-11-03 09:30:02.001  INFO 1916 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'me.ruslanys.telegraff.autoconfigure.TelegraffAutoConfiguration$Companion' of type [me.ruslanys.telegraff.autoconfigure.TelegraffAutoConfiguration$Companion] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-03 09:30:02.003  INFO 1916 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesValidator' of type [me.ruslanys.telegraff.autoconfigure.property.TelegramPropertiesValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-03 09:30:02.775  INFO 1916 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2019-11-03 09:30:02.869  INFO 1916 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-11-03 09:30:02.870  INFO 1916 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.26]
2019-11-03 09:30:03.312  INFO 1916 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-11-03 09:30:03.315  INFO 1916 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3558 ms
2019-11-03 09:30:04.130  INFO 1916 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.openapi.util.JDOMUtil$2 (file:/C:/Users/servb/Documents/Shared/telegraff/telegraff-sample/build/install/telegraff-sample/lib/kotlin-compiler-embeddable-1.3.21.jar) to constructor com.sun.xml.internal.stream.XMLInputFactoryImpl()
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.openapi.util.JDOMUtil$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:90)
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:68)
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.findBinFile(PathManager.java:171)
        at org.jetbrains.kotlin.com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoader.java:338)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:48)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:62)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:54)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.setFileAttributes(ZipHandler.java:62)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:44)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:39)
        at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:61)
        at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:54)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.getCachedZipFileHandle(ZipHandler.java:84)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.acquireZipHandle(ZipHandler.java:131)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandlerBase.createEntriesMap(ZipHandlerBase.java:44)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:197)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:42)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.lambda$new$0(CoreJarFileSystem.java:33)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:181)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:45)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:44)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:415)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:394)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.access$contentRootToVirtualFile(KotlinCoreEnvironment.kt:127)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$5.invoke(KotlinCoreEnvironment.kt:272)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$5.invoke(KotlinCoreEnvironment.kt:127)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:70)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:279)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:127)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:463)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericReplChecker.kt:62)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:54)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:52)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:45)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:51)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:53)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.createState(KotlinJsr223JvmLocalScriptEngine.kt:57)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.createState$default(KotlinJsr223JvmScriptEngineBase.kt:46)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.getCurrentState(KotlinJsr223JvmScriptEngineBase.kt:53)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.nextCodeLine(KotlinJsr223JvmScriptEngineBase.kt:44)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:59)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:33)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
        at me.ruslanys.telegraff.core.dsl.DefaultHandlersFactory.compile(DefaultHandlersFactory.kt:48)
        at me.ruslanys.telegraff.core.dsl.DefaultHandlersFactory.<init>(DefaultHandlersFactory.kt:33)
        at me.ruslanys.telegraff.autoconfigure.TelegraffServletWebConfiguration.handlersFactory(TelegraffServletWebConfiguration.kt:81)
        at me.ruslanys.telegraff.autoconfigure.TelegraffServletWebConfiguration$$EnhancerBySpringCGLIB$$d5de5806.CGLIB$handlersFactory$6(<generated>)
        at me.ruslanys.telegraff.autoconfigure.TelegraffServletWebConfiguration$$EnhancerBySpringCGLIB$$d5de5806$$FastClassBySpringCGLIB$$f2f44b4b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
        at me.ruslanys.telegraff.autoconfigure.TelegraffServletWebConfiguration$$EnhancerBySpringCGLIB$$d5de5806.handlersFactory(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
        at me.ruslanys.telegraff.sample.ApplicationKt.main(Application.kt:13)
2019-11-03 09:30:15.374  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for CounterHandler.kts took 10361 ms
2019-11-03 09:30:16.401  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for HtmlHandler.kts took 1011 ms
2019-11-03 09:30:17.431  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for MarkdownHandler.kts took 1024 ms
2019-11-03 09:30:18.924  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for NameHandler.kts took 1480 ms
2019-11-03 09:30:19.642  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for PhotoHandler.kts took 710 ms
2019-11-03 09:30:21.298  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for RestHandler.kts took 1653 ms
2019-11-03 09:30:22.778  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for TaxiHandler.kts took 1443 ms
2019-11-03 09:30:23.527  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for VoiceHandler.kts took 736 ms
2019-11-03 09:30:24.049  INFO 1916 --- [           main] m.r.t.core.dsl.DefaultHandlersFactory    : Compilation for WelcomeHandler.kts took 519 ms
2019-11-03 09:30:24.973  INFO 1916 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2019-11-03 09:30:24.981  INFO 1916 --- [           main] m.r.telegraff.sample.ApplicationKt       : Started ApplicationKt in 27.908 seconds (JVM running for 34.052)
2019-11-03 09:30:24.987  INFO 1916 --- [           main] m.r.t.core.client.TelegramPollingClient  : Telegram client: POLLING
```

**Comment by ruslanys** [comment]
Hello Sergey. That's strange...
Looks like you have such a problem because you are using Windows :) I see the exception is going from Kotlin-Embedded compiler. That's interesting. Let's figure out what's wrong. Probably, it makes sense to report an issue for them.

Could you please try to upgrade your Kotlin version to the latest one (1.3.50) and check it again?

**Comment by SerVB** [comment]
Hi!

I've just checked: 1.3.50 and 1.3.60 – the same error text.

If I run on Linux, no errors are printed.
